name: gas_710
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase  
  cloud_firestore: ^0.13.4   # https://pub.dev/packages/cloud_firestore
  firebase_auth: ^0.15.4      # https://pub.dev/packages/firebase_auth
  google_sign_in: ^4.1.1      # https://pub.dev/packages/google_sign_in

  # GOOGLE MAPS
  google_maps_flutter: ^0.5.22  # https://pub.dev/packages/google_maps_flutter
  flutter_polyline_points: ^0.1.0 # https://pub.dev/packages/flutter_polyline_points
  geolocator: ^5.2.1          # https://pub.dev/packages/geolocator
  geocoder: ^0.2.1            # https://pub.dev/packages/geocoder
  flutter_google_places: ^0.2.3 # https://pub.dev/packages/flutter_google_places
  google_maps_webservice: ^0.0.16 # https://pub.dev/packages/google_maps_webservice
  contacts_service: ^0.3.10   # https://pub.dev/packages/contacts_service
  permission_handler: ^4.2.0+hotfix.3 # https://pub.dev/packages/permission_handler
  intl: ^0.16.1               # https://pub.dev/packages/intl
  sliding_up_panel: ^1.0.0    # https://pub.dev/packages/sliding_up_panel

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2     # https://pub.dev/packages/cupertino_icons
  fluttertoast: ^3.1.3        # https://pub.dev/packages/fluttertoast

  # Payment Page
  url_launcher: ^5.4.1        # https://pub.dev/packages/url_launcher
  webview_flutter: ^0.3.19+8  # https://pub.dev/packages/webview_flutter
  device_apps: ^1.0.9         # https://pub.dev/packages/device_app

  # Database Packages
  sqflite: any                # https://pub.dev/packages/sqflite

  # Creating PDF
  pdf: ^1.5.0                 # https://pub.dev/packages/pdf

  # Creating txt
  path_provider: ^1.6.5       # https://pub.dev/packages/path_provider

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
